# for Watermill development purposes.
# For Watermill based application docker please check https://watermill.io/docs/getting-started/

version: '3'
services:
  nats:
    image: nats
    ports:
      - "0.0.0.0:4222:4222"
    restart: unless-stopped
    entrypoint: ["/nats-server", "--js"]
