# for Watermill development purposes.
# For Watermill based application docker please check https://watermill.io/docs/getting-started/

version: '3'
services:
  nats:
    image: nats:2-alpine
    ports:
      - "0.0.0.0:4222:4222"
    restart: unless-stopped
    command: ["--js"]
